/// Flutter icons Bag
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bag
///      fonts:
///       - asset: fonts/Bag.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bag {
  Bag._();

  static const _kFontFam = 'Bag';
  static const String? _kFontPkg = null;

  static const IconData bag = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
