/// Flutter icons InCompleteJobs
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InCompleteJobs
///      fonts:
///       - asset: fonts/InCompleteJobs.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InCompleteJobs {
  InCompleteJobs._();

  static const _kFontFam = 'InCompleteJobs';
  static const String? _kFontPkg = null;

  static const IconData incompletejob = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
