/// Flutter icons PaymentMethod
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PaymentMethod
///      fonts:
///       - asset: fonts/PaymentMethod.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PaymentMethod {
  PaymentMethod._();

  static const _kFontFam = 'PaymentMethod';
  static const String? _kFontPkg = null;

  static const IconData cheque =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mixed =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paynow =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pending_payment =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData billing =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
