/// Flutter icons SideMenuIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SideMenuIcons
///      fonts:
///       - asset: fonts/SideMenuIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SideMenuIcons {
  SideMenuIcons._();

  static const _kFontFam = 'SideMenuIcons';
  static const String? _kFontPkg = null;

  static const IconData logout = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job_history = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData return_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spareparts_history = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_iconall_icons = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_history = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
